### ISSUE TITLE
Settings page is broken when trying to show a bad image in the hull selection

### ISSUE THREAD

**Issue by cedricve** [kerberos-io/web#68]
Example error

    [2017-01-06 21:21:16] production.ERROR: exception 'Intervention\Image\Exception\NotReadableException' with message 'Unable to init from given url (http://localhost:32778//capture//1483734064_5-95654_frontdoor_regionCoordinates_numberOfChanges_587.jpg).' in /var/www/web/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php:68
    Stack trace:
    #0 /var/www/web/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php(287): Intervention\Image\AbstractDecoder->initFromUrl('http://localhos...')
    #1 /var/www/web/vendor/intervention/image/src/Intervention/Image/AbstractDriver.php(64): Intervention\Image\AbstractDecoder->init('http://localhos...')
    #2 /var/www/web/vendor/intervention/image/src/Intervention/Image/ImageManager.php(50): Intervention\Image\AbstractDriver->init('http://localhos...')
    #3 /var/www/web/bootstrap/compiled.php(1450): Intervention\Image\ImageManager->make('http://localhos...')
    #4 /var/www/web/app/storage/views/3aa7a583d3e829eda4b3ec6556583692(10): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
    #5 /var/www/web/app/storage/views/3aa7a583d3e829eda4b3ec6556583692(10): Intervention\Image\Facades\Image::make('http://localhos...')

**Comment by cedricve** [comment]
Fixed by 3386ad6e149c8c7e917e5e6486be4b1a964972cd
